### ISSUE TITLE
My Aircraft Request! 

### ISSUE THREAD

**Issue by PawlomYT** [geofs-plugins/aircraft-warehouse#34] opened 2018-03-02 19:06 UTC
**The model I want**: Airbus A340-600

**The livery I want**: Virgin Atlantic

**Special reason for desiring this aircraft**:
Because this aircraft is unique with its quad engine, single floor design and only one of its kind!
**Enter some pictures of a real-life aircraft here**:

http://cargo.virgin-atlantic.com/gb/en/our-services/our-fleet.html

https://www.airlinereporter.com/2017/02/upper-class-virgin-atlantic-bubbles-a340-atlanta-london/

http://airteamnews.blogspot.com/2009/05/airbus-a340-600-virgin-atlantic-airways.html

https://www.airplane-pictures.net/photo/6810/g-vnap-virgin-atlantic-airbus-a340-600/

https://1400reviews.com/2017/05/19/virgin-atlantic-a340-600-g-veil-gemini-jets-1400-gjvir1634may2017/

Thanks you!

**Comment by yotam180** [comment] 2018-03-02 19:31
Seems like a duplicate of #21

**Closed by yotam180** 2018-03-02 19:31 UTC
